/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz.Isabella;

import Gestion.Clases.Pojo.GestionCalzado;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS 7
 */
public class BusquedaCalzadoPagina extends javax.swing.JFrame {

    Connection cn;
    ResultSet rs;
    PreparedStatement ps;
    ResultSetMetaData rsm;
    DefaultTableModel dtm;
    GestionCalzado gcl = new GestionCalzado();
    
    /**
     * Creates new form BusquedaCalzadoPagina
     */
    public BusquedaCalzadoPagina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCalzado = new javax.swing.JTable();
        btnConsultarCalzadoPagina = new javax.swing.JButton();
        lblBusquedaCalzado = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaCalzado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pagina", "Codigo", "Talla", "Color", "Precio", "Existencia"
            }
        ));
        TablaCalzado.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(TablaCalzado);

        btnConsultarCalzadoPagina.setText("Consultar Calzado");
        btnConsultarCalzadoPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCalzadoPaginaActionPerformed(evt);
            }
        });

        lblBusquedaCalzado.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        lblBusquedaCalzado.setText("Busqueda Calzado");

        btnRegresar.setText("<< Regesar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRegresar)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultarCalzadoPagina))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblBusquedaCalzado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(lblBusquedaCalzado)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarCalzadoPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarCalzadoPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCalzadoPaginaActionPerformed
        
        try
        {
//            Class.forName("com.sqlserver.jdbc.Driver");
            cn= DriverManager.getConnection("jdbc:sqlserver://kenan-pc:1433;databaseName=Isabella","sa","123");
            ps= cn.prepareStatement("SELECT[Página],[Código],[Talla],[Color],[Precio],[Existencia]FROM [dbo].[Calzado]");
            rs=ps.executeQuery();
            rsm=rs.getMetaData();
            ArrayList<Object[]> datos = new ArrayList<Object[]>();
            while(rs.next())
            {
                Object[] filas = new Object[rsm.getColumnCount()];
                for (int i = 0; i < filas.length; i++) 
                {
                    filas[i]= rs.getObject(i+1);
                }
                datos.add(filas);
            }
            dtm=(DefaultTableModel)this.TablaCalzado.getModel();
            for (int i = 0; i < datos.size(); i++) 
            {
                dtm.addRow(datos.get(i));
            }
//            gcl.getObjCalzado().setCodigo(txtBusquedaPagina.getText());
//            try
//            {
//                gcl.ConsultaPagina();
//                JOptionPane.showMessageDialog(this, "Calzado Encontrado");
//                txtBusquedaPagina.grabFocus();
//            }
//            catch(SQLException ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
        }
        catch(SQLException ex){ JOptionPane.showInputDialog(null, ex.getMessage()) ;}
    }//GEN-LAST:event_btnConsultarCalzadoPaginaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        InterfazCalzado cl = new InterfazCalzado();
        cl.show();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaCalzadoPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaCalzadoPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaCalzadoPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaCalzadoPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaCalzadoPagina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCalzado;
    private javax.swing.JButton btnConsultarCalzadoPagina;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusquedaCalzado;
    // End of variables declaration//GEN-END:variables
}
